### ISSUE TITLE
DocumentStore error with v0.0.12

### ISSUE THREAD

**Issue by dmartinol** [milvus-io/milvus-haystack#39]
## Steps to reproduce the issue
- Create a `DocumentStore` with field `collection_name` set
- Connect it to an `MilvusEmbeddingRetriever` in a `Pipeline`
- Run the `Pipeline`
-An error is raised
```
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/haystack/core/pipeline/pipeline.py", line 76, in _run_component
    res: Dict[str, Any] = instance.run(**inputs)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/milvus_haystack/milvus_embedding_retriever.py", line 67, in run
    docs = self.document_store._embedding_retrieval(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/milvus_haystack/document_store.py", line 778, in _embedding_retrieval
    distance_to_score_fn = self._select_score_fn()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/milvus_haystack/document_store.py", line 904, in _select_score_fn
    metric_type = self.index_params.get("metric_type", None)
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
(venv) dmartino@dmartino-mac instructlab % 
```
## Initial investigation
* Line 904 accesses `self.index_params` field with no `is None` check. 
```python
        metric_type = self.index_params.get("metric_type", None)
```
* The field is `None` because in `_create_index` the call to `self._get_index()` returns the collection index:
```python
    def _create_index(self) -> None:
        """Create an index on the collection"""
        from pymilvus import Collection, MilvusException

        if isinstance(self.col, Collection) and self._get_index() is None:
...
```
## Originated by PR
This change was introduced in https://github.com/milvus-io/milvus-haystack/pull/37

FYI, @zc277584121

**Comment by zc277584121** [comment]
@dmartinol  Thank you for your feedback. So in this situation, the `index_params` in `MilvusDocumentStore` instance is None , but actually there exists an index in milvus collection, right?

**Comment by zc277584121** [comment]
fixed : https://github.com/milvus-io/milvus-haystack/pull/40/commits/8ef71cdd57f35e53688859a92cb52cabd5fb3cfb
